# SITE CONFIGURATION
title: net.work
# your site title
author: timeforplanb # You :P
description: > 
 | networking | linux | project management | programming | blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://network.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# SEO PLUGIN
social:
  name: timeforplanb
  links:
#    - https://twitter.com/BenBalter
#    - https://www.facebook.com/ben.balter
#    - https://www.linkedin.com/in/BenBalter
     - https://plus.google.com/116393668939937207464
     - https://github.com/network
#    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
# - {name: 'HOME', link: '/'}
  - {name: 'Linux', link: '/linux'}
  - {name: 'Code', link: '/code'}
  - {name: 'Networking', link: '/networking'}
  - {name: 'Management', link: '/management'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

#  tagline: >
#  Modern Jekyll theme focused on speed performance &amp; SEO best practices

# hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: timeforplanb123@gmail.com # email for form submission

twitter_username: timeforplanb1  # replace with your_twitter_username or comment to remove link from footer
github_username:  network  # replace with your_github_username or comment to remove link from footer
instagram_username: __timeforplanb # replace with your_instagram_username or comment to remove link from footer
#facebook_username: # replace with your_facebook_username or comment to remove link from footer
googleplus_username: 116393668939937207464 # replace with your_googleplus_username or comment to remove link from footer

disqus:
  shortname: net-work # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg
  
incremental: true

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 6